# https://taskfile.dev

version: '3'

env:
  # App
  API_NAME: api-credit
  APP_SECRET: B@nk4I
  # Database
  DATABASE_DRIVER: pgx
  DATABASE_URL: postgres://postgres:123456@192.168.100.47/credits
  DATABASE_MAX_OPEN_CONNECTIONS: 25
  DATABASE_MAX_IDDLE_CONNECTIONS: 25
  DATABASE_MAX_IDDLE_TIME: 15m
  # HTTP
  HTTP_SERVER_IDLE_TIMEOUT: 60s
  PORT: 8080
  HTTP_SERVER_READ_TIMEOUT: 1s
  HTTP_SERVER_WRITE_TIMEOUT: 2s

tasks:
  build:
    cmds:
      - env CGO_ENABLED=0 GOOS=linux go build -ldflags '-w -s' -a -installsuffix cgo -o bin/$API_NAME ./cmd/main.go

  run:
    deps:
      - build
    cmds:
      - ./bin/$API_NAME

  test:
    desc: Run all tests ignoring cache
    cmds:
      - go test -cover -v ./... -count=1

  clean:
    cmds:
      - rm -fr ./bin

    db_up:
      cmds:
        - migrate -path=./migrations -database=$(DATABASE_URL) up

    db_down:
      cmds:
        - migrate -path=./migrations -database=$(DATABASE_URL) down

    mocks:
      cmds:
        - mockgen -source .\interfaces\credit_assigner.go -destination .\internal\mocks\credit_service.go -package mocks
        - mockgen -source .\interfaces\credit_repository.go -destination .\internal\mocks\credit_repository.go -package mocks