CREATE TABLE IF NOT EXISTS credit_assigns(
     id BIGSERIAL NOT NULL PRIMARY KEY,
     invest INT NOT NULL DEFAULT 0,
     credit_300 INT NOT NULL DEFAULT 0,
     credit_500 INT NOT NULL DEFAULT 0,
     credit_700 INT NOT NULL DEFAULT 0,
     status SMALLINT NOT NULL DEFAULT 0,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP,
     deleted_at TIMESTAMP
);